[2024-05-13T04:37:30.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T04:37:30.032+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-08T00:00:00+00:00 [queued]>
[2024-05-13T04:37:30.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-08T00:00:00+00:00 [queued]>
[2024-05-13T04:37:30.037+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-13T04:37:30.044+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet> on 2021-10-08 00:00:00+00:00
[2024-05-13T04:37:30.054+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6512) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-13T04:37:30.059+0000] {standard_task_runner.py:63} INFO - Started process 6526 to run task
[2024-05-13T04:37:30.060+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v02', 'greet', 'scheduled__2021-10-08T00:00:00+00:00', '--job-id', '1008', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp5fu_av7p']
[2024-05-13T04:37:30.063+0000] {standard_task_runner.py:91} INFO - Job 1008: Subtask greet
[2024-05-13T04:37:30.148+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-08T00:00:00+00:00 [running]> on host f1ddc6e75993
[2024-05-13T04:37:30.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mani' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v02' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2021-10-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-08T00:00:00+00:00'
[2024-05-13T04:37:30.256+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T04:37:30.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T04:37:30.269+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    print(f"Hello World ! My name is {name},"
                                      ^^^^
NameError: name 'name' is not defined
[2024-05-13T04:37:30.278+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v02, task_id=greet, run_id=scheduled__2021-10-08T00:00:00+00:00, execution_date=20211008T000000, start_date=20240513T043730, end_date=20240513T043730
[2024-05-13T04:37:30.289+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1008 for task greet (name 'name' is not defined; 6526)
[2024-05-13T04:37:30.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T04:37:30.340+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
