[2024-05-13T04:32:29.419+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T04:32:29.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-06T00:00:00+00:00 [queued]>
[2024-05-13T04:32:29.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-06T00:00:00+00:00 [queued]>
[2024-05-13T04:32:29.439+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-13T04:32:29.445+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet> on 2021-10-06 00:00:00+00:00
[2024-05-13T04:32:29.449+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-13T04:32:29.449+0000] {standard_task_runner.py:63} INFO - Started process 6325 to run task
[2024-05-13T04:32:29.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v02', 'greet', 'scheduled__2021-10-06T00:00:00+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp6dy6z5jn']
[2024-05-13T04:32:29.450+0000] {standard_task_runner.py:91} INFO - Job 986: Subtask greet
[2024-05-13T04:32:29.477+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v02.greet scheduled__2021-10-06T00:00:00+00:00 [running]> on host f1ddc6e75993
[2024-05-13T04:32:29.524+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mani' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v02' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2021-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-06T00:00:00+00:00'
[2024-05-13T04:32:29.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T04:32:29.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T04:32:29.535+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    print(f"Hello World ! My name is {name},"
                                      ^^^^
NameError: name 'name' is not defined
[2024-05-13T04:32:29.543+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v02, task_id=greet, run_id=scheduled__2021-10-06T00:00:00+00:00, execution_date=20211006T000000, start_date=20240513T043229, end_date=20240513T043229
[2024-05-13T04:32:29.556+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 986 for task greet (name 'name' is not defined; 6325)
[2024-05-13T04:32:29.588+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T04:32:29.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
